/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quanlicuahangsuachua;

import Connect.Data;
import java.sql.*;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author huyduy
 */
public class NhapPhuTung extends javax.swing.JFrame {
private Connection con;
private ResultSet rs;
private PreparedStatement stmt;

    /**
     * Creates new form NhapPhuTung
     */
    public NhapPhuTung() {
        initComponents();
        this.setLocationRelativeTo(null);
        try {
            con = Data.getConnection();
        } catch (Exception e) {
        }
        showtbNhapPhuTung();
    }
public void showtbNhapPhuTung(){
    Vector cols = new Vector();
    cols.addElement("ID Phụ tùng");
    cols.addElement("Tên Phụ Tùng");
        cols.addElement("Nhà Cung Cấp");
        cols.addElement("Ngày nhập");
        cols.addElement("Số lượng");
        cols.addElement("Giá thành nhập");
        cols.addElement("Giá thành xuất");
        //tao vector du lieu
             Vector data1 = new Vector();
        String sql = "SELECT * FROM demoqlchscxm.nhapphutung";
        try {
            stmt = con.prepareStatement(sql);
            rs = stmt.executeQuery(sql); //dung querry vi dung cau lenh select
            while(rs.next()){     //duyet du lieu
                 Vector npt1 = new Vector();
                 npt1.addElement(rs.getInt("idphutung"));
                 npt1.addElement(rs.getString("tenPhuTung"));
                 npt1.addElement(rs.getString("nhaCungCap"));
                 //stmt.setDate(3,java.sql.Date.valueOf(txtNgayNhap.getText()));
                 npt1.addElement(rs.getDate("ngayNhap"));
                 npt1.addElement(rs.getInt("soLuong"));
                 npt1.addElement(rs.getInt("giaThanh"));
                 npt1.addElement(rs.getInt("giaThanhXuat"));
                 data1.add(npt1);     
            }
            
        } catch (Exception e) {
        }
        
        tbNhapPhuTung.setModel(new DefaultTableModel(data1, cols));
   this.lbTongPhuTung.setText("Tổng số có "+this.tbNhapPhuTung.getRowCount()+" phụ tùng"); 

}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtTenPhuTung = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtNhaCungCap = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtNgayNhap = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtSoLuong = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtGiaThanh = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtGiaThanhXuat = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbNhapPhuTung = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        btnReset = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        lbTongPhuTung = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("jLabel1");

        jTextField1.setText("jTextField1");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton1.setText("jButton1");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(302, 302, 302)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 140, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel3.setLayout(new java.awt.GridLayout(7, 2));

        jLabel5.setText("ID Phụ Tùng");
        jPanel3.add(jLabel5);
        jPanel3.add(txtID);

        jLabel3.setText("Tên Phụ Tùng");
        jPanel3.add(jLabel3);
        jPanel3.add(txtTenPhuTung);

        jLabel6.setText("Nhà Cung Cấp");
        jPanel3.add(jLabel6);
        jPanel3.add(txtNhaCungCap);

        jLabel4.setText("Ngày Nhập");
        jPanel3.add(jLabel4);
        jPanel3.add(txtNgayNhap);

        jLabel7.setText("Số Lượng");
        jPanel3.add(jLabel7);
        jPanel3.add(txtSoLuong);

        jLabel2.setText("Giá Thành Nhập");
        jPanel3.add(jLabel2);
        jPanel3.add(txtGiaThanh);

        jLabel8.setText("Giá Thành Xuất");
        jPanel3.add(jLabel8);

        txtGiaThanhXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGiaThanhXuatActionPerformed(evt);
            }
        });
        jPanel3.add(txtGiaThanhXuat);

        tbNhapPhuTung.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7"
            }
        ));
        tbNhapPhuTung.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbNhapPhuTungMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbNhapPhuTung);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(162, 162, 162))
        );

        jPanel4.setLayout(new java.awt.GridLayout(1, 3));

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        jPanel4.add(btnReset);

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanel4.add(btnDelete);

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanel4.add(btnUpdate);

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        jPanel4.add(btnAdd);

        jPanel5.setLayout(new java.awt.GridLayout(1, 3));

        jButton2.setText("Xem Thống Kê");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton2);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/close-icon-32.png"))); // NOI18N
        jButton3.setText("Thoát");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton3);

        lbTongPhuTung.setText("Số loại phụ tùng có trong kho");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbTongPhuTung, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbTongPhuTung, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(117, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
      String sql = "INSERT INTO demoqlchscxm.nhapphutung (tenPhuTung,nhaCungCap,ngayNhap,soLuong,giaThanh,giaThanhXuat,soLuongConLai) VALUES (?,?,?,?,?,?,?)";
        try {
            stmt = con.prepareStatement(sql);
            stmt.setString(1, txtTenPhuTung.getText());
        stmt.setString(2, txtNhaCungCap.getText());
        stmt.setDate(3,java.sql.Date.valueOf(txtNgayNhap.getText()));
        stmt.setInt(4,Integer.parseInt(txtSoLuong.getText()));
        stmt.setInt(5,Integer.parseInt(txtGiaThanh.getText()));
        stmt.setInt(6,Integer.parseInt(txtGiaThanhXuat.getText()));
        stmt.setInt(7,Integer.parseInt(txtSoLuong.getText()));//gan soLuongConLai = soLuong tu dau
        stmt.executeUpdate();

        } catch (Exception e) {
        }
        showtbNhapPhuTung();
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
       String sql = "UPDATE demoqlchscxm.nhapphutung SET tenPhuTung = ?,nhaCungCap = ?,ngayNhap = ?,soLuong = ?,giaThanh =?, giaThanhXuat=?,soLuongConLai = ? WHERE idphutung = ?";
        try {
            int id = Integer.parseInt(txtID.getText());
            stmt = con.prepareStatement(sql);
            stmt.setString(1,txtTenPhuTung.getText());
            stmt.setString(2,txtNhaCungCap.getText());
            stmt.setDate(3,java.sql.Date.valueOf(txtNgayNhap.getText()));
            stmt.setInt(4,Integer.parseInt(txtSoLuong.getText()));
            stmt.setInt(5,Integer.parseInt(txtGiaThanh.getText()));
            stmt.setInt(6,Integer.parseInt(txtGiaThanhXuat.getText()));
            stmt.setInt(7,Integer.parseInt(txtSoLuong.getText()));
            stmt.setInt(8,id);
            
            stmt.executeUpdate();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Chon 1 user truoc khi update");
        }
        showtbNhapPhuTung();
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void tbNhapPhuTungMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbNhapPhuTungMouseClicked
                int row = tbNhapPhuTung.getSelectedRow();
        if(row != -1 ){
            
          
            txtID.setText(tbNhapPhuTung.getValueAt(row, 0).toString());
    
            txtTenPhuTung.setText(tbNhapPhuTung.getValueAt(row, 1).toString());
            txtNhaCungCap.setText(tbNhapPhuTung.getValueAt(row, 2).toString());
            txtNgayNhap.setText(tbNhapPhuTung.getValueAt(row, 3).toString());
            txtSoLuong.setText(tbNhapPhuTung.getValueAt(row, 4).toString());
            txtGiaThanh.setText(tbNhapPhuTung.getValueAt(row, 5).toString());
             txtGiaThanhXuat.setText(tbNhapPhuTung.getValueAt(row, 6).toString());
        }

    }//GEN-LAST:event_tbNhapPhuTungMouseClicked

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        String sql = "DELETE FROM demoqlchscxm.nhapphutung WHERE idphutung = ?";
        int choice = JOptionPane.showConfirmDialog(this, "Are you sure?");
        if(choice == JOptionPane.YES_OPTION){
            try {
               int id = Integer.parseInt(txtID.getText());
               stmt = con.prepareStatement(sql);
               stmt.setInt(1, id);
               stmt.executeUpdate();
               
            } catch (Exception e){
                JOptionPane.showMessageDialog(this, "Chọn user trước khi thực hiện");
            }
        }
        showtbNhapPhuTung();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
          Main Frmm=new Main();
          this.setVisible(false);
          Frmm.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        


         
         this.txtGiaThanh.setText(null);
         this.txtGiaThanhXuat.setText(null);
         this.txtSoLuong.setText(null);
         this.txtNgayNhap.setText(null);
         this.txtID.setText(null);
         this.txtNhaCungCap.setText(null);
         this.txtTenPhuTung.setText(null);
         showtbNhapPhuTung();
    }//GEN-LAST:event_btnResetActionPerformed

    private void txtGiaThanhXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGiaThanhXuatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGiaThanhXuatActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        ThongKePhuTung tkpt = new ThongKePhuTung();
         this.setVisible(false);
             tkpt.setVisible(true);  
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NhapPhuTung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NhapPhuTung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NhapPhuTung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NhapPhuTung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NhapPhuTung().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lbTongPhuTung;
    private javax.swing.JTable tbNhapPhuTung;
    private javax.swing.JTextField txtGiaThanh;
    private javax.swing.JTextField txtGiaThanhXuat;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtNgayNhap;
    private javax.swing.JTextField txtNhaCungCap;
    private javax.swing.JTextField txtSoLuong;
    private javax.swing.JTextField txtTenPhuTung;
    // End of variables declaration//GEN-END:variables
}
