/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quanlicuahangsuachua;


import Connect.Data;
import com.itextpdf.awt.PdfPrinterGraphics2D;
import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Document;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Image;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfAWriter;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Font;
import java.awt.HeadlessException;
import java.io.FileOutputStream;
import java.sql.*;
import javax.swing.JOptionPane;


import java.util.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.html.parser.Element;

/**
 *
 * @author huyduy
 */
public class PhieuSuaChua extends javax.swing.JFrame {
private Connection con;
private ResultSet rs;
private PreparedStatement stmt;
    /**
     * Creates new form PhieuSuaChua
     */
    public PhieuSuaChua() {
      
          initComponents();
        this.setLocationRelativeTo(null);
        try {
            con = Data.getConnection();
        } catch (Exception e) {
        }
        showtbPhieuSuaChua();
    }

    
    public void showtbPhieuSuaChua(){
        Vector cols = new Vector();
        cols.addElement("ID PSC");
    cols.addElement("NVPV");
    cols.addElement("Ngày nhận");
        cols.addElement("Tên KH");
        cols.addElement("BKS");
        cols.addElement("Mobile");
        cols.addElement("Ngày Giao");
        cols.addElement("NVSC");
        cols.addElement("Tình trạng trước");
        cols.addElement("Ngay Trả");
        cols.addElement("Tổng Phí");
        cols.addElement("Tình trạng sau");
        //tao vector du lieu
             Vector data3 = new Vector();
        String sql = "SELECT * FROM demoqlchscxm.phieusuachua";
        try {
            stmt = con.prepareStatement(sql);
            rs = stmt.executeQuery(sql); //dung querry vi dung cau lenh select
            while(rs.next()){     //duyet du lieu
                 Vector psc = new Vector();
                 psc.addElement(rs.getInt("idPhieuSuaChua"));
                 psc.addElement(rs.getString("nhanVienPhucVu"));
                 psc.addElement(rs.getDate("ngayNhan"));
                 psc.addElement(rs.getString("tenKhachHang"));
                 psc.addElement(rs.getString("bienKiemSoat"));
                 //stmt.setDate(3,java.sql.Date.valueOf(txtNgayNhap.getText()));
                 
                 psc.addElement(rs.getString("dienThoai"));
                 psc.addElement(rs.getDate("ngayGiao"));
                 psc.addElement(rs.getString("nhanVienSuaChua"));
                 psc.addElement(rs.getString("tinhTrangTruoc"));
                 psc.addElement(rs.getDate("ngayTra"));
             
                 psc.addElement(rs.getInt("tongPhi"));
                psc.addElement(rs.getString("tinhTrangSau"));
                 data3.add(psc);     
            }
            
        } catch (Exception e) {
        }
        
        tbPhieuSuaChua.setModel(new DefaultTableModel(data3, cols));
   this.lbPhieuSuaChua.setText("Tổng số có "+this.tbPhieuSuaChua.getRowCount()+" phụ tùng"); 

    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNhanVienPhucVu = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNgayNhan = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtTenKhachHang = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtBienKiemSoat = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtDienThoai = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtNgayTra = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtTongPhi = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtTinhTrangSau = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txtNgayGiao = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtNhanVienSuaChua = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtTinhTrangTruoc = new javax.swing.JTextArea();
        jLabel12 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btnReset = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jTextField11 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbPhieuSuaChua = new javax.swing.JTable();
        btnPrint = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        btnXemThongKe = new javax.swing.JButton();
        lbPhieuSuaChua = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("PHIẾU SỬA CHỮA");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(298, 298, 298)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "NHẬN XE", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18))); // NOI18N
        jPanel3.setLayout(new java.awt.GridLayout(6, 2));

        jLabel13.setText("Mã số Phiếu Sửa Chữa:");
        jPanel3.add(jLabel13);
        jPanel3.add(txtID);

        jLabel2.setText("Nhân viên phục vụ:");
        jPanel3.add(jLabel2);
        jPanel3.add(txtNhanVienPhucVu);

        jLabel3.setText("Ngày nhận: ");
        jPanel3.add(jLabel3);
        jPanel3.add(txtNgayNhan);

        jLabel4.setText("Tên khách hàng:");
        jPanel3.add(jLabel4);
        jPanel3.add(txtTenKhachHang);

        jLabel5.setText("Biển kiểm soát:");
        jPanel3.add(jLabel5);
        jPanel3.add(txtBienKiemSoat);

        jLabel6.setText("Điện thoại:");
        jPanel3.add(jLabel6);
        jPanel3.add(txtDienThoai);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "TRẢ XE", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18))); // NOI18N

        jPanel6.setLayout(new java.awt.GridLayout(2, 2));

        jLabel7.setText("Ngày trả:");
        jPanel6.add(jLabel7);
        jPanel6.add(txtNgayTra);

        jLabel8.setText("Tổng phí:");
        jPanel6.add(jLabel8);
        jPanel6.add(txtTongPhi);

        txtTinhTrangSau.setColumns(20);
        txtTinhTrangSau.setRows(5);
        jScrollPane1.setViewportView(txtTinhTrangSau);

        jLabel9.setText("Tình trạng sau:");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "GIAO XE", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18))); // NOI18N

        jPanel8.setLayout(new java.awt.GridLayout(2, 2));

        jLabel10.setText("Ngày giao: ");
        jPanel8.add(jLabel10);
        jPanel8.add(txtNgayGiao);

        jLabel11.setText("Nhân viên sửa chữa:");
        jPanel8.add(jLabel11);
        jPanel8.add(txtNhanVienSuaChua);

        txtTinhTrangTruoc.setColumns(20);
        txtTinhTrangTruoc.setRows(5);
        jScrollPane2.setViewportView(txtTinhTrangTruoc);

        jLabel12.setText("Tình trạng trước:");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2))))
        );

        jPanel4.setLayout(new java.awt.GridLayout(1, 4));

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        jPanel4.add(btnReset);

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanel4.add(btnDelete);

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanel4.add(btnUpdate);

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        jPanel4.add(btnAdd);

        jTextField11.setText("jTextField11");

        jButton1.setText("jButton1");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(347, Short.MAX_VALUE)
                .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextField11)
            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        tbPhieuSuaChua.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8", "Title 9", "Title 10", "Title 11", "Title 12"
            }
        ));
        tbPhieuSuaChua.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbPhieuSuaChuaMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tbPhieuSuaChua);

        btnPrint.setText("Print");
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });

        jButton7.setText("CTSC");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("Exit");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        btnXemThongKe.setText("Xem TK");
        btnXemThongKe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXemThongKeActionPerformed(evt);
            }
        });

        lbPhieuSuaChua.setText("Số xe đã sửa");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(128, 128, 128))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(166, 166, 166))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 989, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(lbPhieuSuaChua, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnXemThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnXemThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbPhieuSuaChua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 991, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnXemThongKeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXemThongKeActionPerformed
        thongkexe tkx = new thongkexe();
                    this.setVisible(false);
                    tkx.setVisible(true);
    }//GEN-LAST:event_btnXemThongKeActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
         Main Frmm=new Main();
                    this.setVisible(false);
                    Frmm.setVisible(true); 
    }//GEN-LAST:event_jButton8ActionPerformed

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed

         try 
        {Document document = new Document();
        PdfWriter.getInstance(document, new FileOutputStream("E:\\page1.pdf"));
        document.open();
        document.add(new Paragraph("                                                                                                                                              To 1/2  "));
       
       
        document.add(new Paragraph("CUA HANG SUA CHUA XE MoToTech",FontFactory.getFont(FontFactory.TIMES_BOLD,18,Font.BOLD,BaseColor.RED)));
        document.add(new Paragraph("Dia chi: 106 Dai La, Hai Ba Trung, Ha Noi"));
        document.add(new Paragraph("Dien Thoai: 04(3) 737 848"));
        document.add(new Paragraph("-------------------------------------------------------------------------------------------------"));
        //document.add(new Paragraph("                                                                                     "));
        document.add(new Paragraph("HOA DON THANH TOAN ",FontFactory.getFont(FontFactory.TIMES_BOLD,18,Font.BOLD,BaseColor.BLUE)));
        document.add(new Paragraph(new java.util.Date().toString()));
         document.add(new Paragraph("                                                                                     "));
            PdfPTable table = new PdfPTable(4);
            
        PdfPCell cell= new PdfPCell( new Paragraph("Nhan Xe, Giao Xe, Tra Xe"));
        cell.setColspan(4);
        cell.setHorizontalAlignment(Element.DEFAULT);
        cell.setBackgroundColor(BaseColor.WHITE);
        table.addCell(cell);
        table.addCell("Ten Khach Hang");
        table.addCell(txtTenKhachHang.getText());
        table.addCell("NVPV");
        table.addCell(txtNhanVienPhucVu.getText());
        table.addCell("Ngay Nhan");
        table.addCell(txtNgayNhan.getText());
        table.addCell("Bien Kiem Soat");
        table.addCell(txtBienKiemSoat.getText());
        table.addCell("Dien Thoai");
        table.addCell(txtDienThoai.getText());
        table.addCell("NVSC");
        table.addCell(txtNhanVienSuaChua.getText());
        table.addCell("Ngay Giao");
        table.addCell(txtNgayGiao.getText());
        table.addCell("Tinh Trang Truoc");
        table.addCell(txtTinhTrangTruoc.getText());
        table.addCell("Ngay Tra");
        table.addCell(txtNgayTra.getText());
        table.addCell("Tinh Trang Sau");
        table.addCell(txtTinhTrangSau.getText());
        table.addCell("Tong Phi");
        table.addCell(txtTongPhi.getText());
        table.addCell(" ");
        table.addCell("");
        
        document.add(table);
       
        
        com.itextpdf.text.List list=new com.itextpdf.text.List();
        
         document.add(new Paragraph("                                                                                     "));
         document.add(new Paragraph("                                                                                     "));
         document.add(new Paragraph("                                                                                     "));
         document.add(new Paragraph("                                                                                     "));
         document.add(new Paragraph("Chan Thanh Cam On Quy Khach!"));
         document.add(new Paragraph("                                                                                     "));
          document.add(new Paragraph("              ")); 
          document.add(new Paragraph("                                                   "));
          document.add(new Paragraph("                                                                                     "));
          document.add(new Paragraph("                                                                             "));
         
          document.add(new Paragraph("                  Nguoi in hoa don                                                             Khach Hang          "));
         document.add(new Paragraph("                      (Ki Ten)                                                                            (Ki Ten)        "));
       
          
          document.add(list);
        
        document.close();
        JOptionPane.showMessageDialog(null, "Trang 1 được lưu trong E:\\page1");
      
        
    }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPrintActionPerformed

    private void tbPhieuSuaChuaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbPhieuSuaChuaMouseClicked
        int row = tbPhieuSuaChua.getSelectedRow();
        if(row != -1 ){
            
          txtID.setText(tbPhieuSuaChua.getValueAt(row, 0).toString());
            txtNhanVienPhucVu.setText(tbPhieuSuaChua.getValueAt(row, 1).toString());
    
            txtNgayNhan.setText(tbPhieuSuaChua.getValueAt(row, 2).toString());
            txtTenKhachHang.setText(tbPhieuSuaChua.getValueAt(row, 3).toString());
            txtBienKiemSoat.setText(tbPhieuSuaChua.getValueAt(row, 4).toString());
            txtDienThoai.setText(tbPhieuSuaChua.getValueAt(row, 5).toString());
            txtNgayGiao.setText(tbPhieuSuaChua.getValueAt(row, 6).toString());
             txtNhanVienSuaChua.setText(tbPhieuSuaChua.getValueAt(row, 7).toString());
              txtTinhTrangTruoc.setText(tbPhieuSuaChua.getValueAt(row, 8).toString());
               txtNgayTra.setText(tbPhieuSuaChua.getValueAt(row, 9).toString());
                txtTongPhi.setText(tbPhieuSuaChua.getValueAt(row, 10).toString());
                 txtTinhTrangSau.setText(tbPhieuSuaChua.getValueAt(row, 11).toString());
         
                 
        }
    }//GEN-LAST:event_tbPhieuSuaChuaMouseClicked

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        String sql = "DELETE FROM demoqlchscxm.phieusuachua WHERE idPhieuSuaChua = ?";
       int choice = JOptionPane.showConfirmDialog(this,"Are you sure?");
        if(choice == JOptionPane.YES_OPTION){
            try {
               int id = Integer.parseInt(txtID.getText());
               stmt = con.prepareStatement(sql);
               stmt.setInt(1, id);
               stmt.executeUpdate();
               
            } catch (Exception e){
                JOptionPane.showMessageDialog(this, "Chọn user trước khi thực hiện");
            }
        }
        showtbPhieuSuaChua();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        String sql = "INSERT INTO demoqlchscxm.phieusuachua (nhanVienPhucVu,ngayNhan,tenKhachHang,bienKiemSoat,dienThoai,ngayGiao,nhanVienSuaChua,tinhTrangTruoc,ngayTra,tongPhi,tinhTrangSau) VALUES (?,?,?,?,?,?,?,?,?,?,?)";
        try {
            stmt = con.prepareStatement(sql);
            

            stmt.setString(1,txtNhanVienPhucVu.getText());
            stmt.setDate(2,java.sql.Date.valueOf(txtNgayNhan.getText()));
            stmt.setString(3, txtTenKhachHang.getText());
            stmt.setString(4,txtBienKiemSoat.getText());
            stmt.setString(5,txtDienThoai.getText());
            stmt.setDate(6,java.sql.Date.valueOf(txtNgayGiao.getText()));
            stmt.setString(7,txtNhanVienSuaChua.getText());
            stmt.setString(8,txtTinhTrangTruoc.getText());
            stmt.setDate(9,java.sql.Date.valueOf(txtNgayTra.getText()));
            stmt.setInt(10,Integer.parseInt(txtTongPhi.getText()));
            stmt.setString(11,txtTinhTrangSau.getText());

        stmt.executeUpdate();

        } catch (Exception e) {
        }
        showtbPhieuSuaChua();
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
         String sql = "UPDATE demoqlchscxm.phieusuachua SET nhanVienPhucVu = ?,ngayNhan = ?,tenKhachHang = ?,bienKiemSoat = ?,dienThoai = ?,ngayGiao = ?,nhanVienSuaChua = ?,tinhTrangTruoc = ?,ngayTra = ?,tongPhi = ?,tinhTrangSau = ? WHERE idPhieuSuaChua = ?";
         try {
            int id = Integer.parseInt(txtID.getText());
             stmt = con.prepareStatement(sql);
            stmt.setString(1,txtNhanVienPhucVu.getText());
            stmt.setDate(2,java.sql.Date.valueOf(txtNgayNhan.getText()));
            stmt.setString(3, txtTenKhachHang.getText());
            stmt.setString(4,txtBienKiemSoat.getText());
            stmt.setString(5,txtDienThoai.getText());
            stmt.setDate(6,java.sql.Date.valueOf(txtNgayGiao.getText()));
            stmt.setString(7,txtNhanVienSuaChua.getText());
            stmt.setString(8,txtTinhTrangTruoc.getText());
            stmt.setDate(9,java.sql.Date.valueOf(txtNgayTra.getText()));
            stmt.setInt(10,Integer.parseInt(txtTongPhi.getText()));
            stmt.setString(11,txtTinhTrangSau.getText());
            stmt.setInt(12,id);
            
            stmt.executeUpdate();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Chon 1 user truoc khi update");
        }
        showtbPhieuSuaChua();
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
//         this.txtGiaThanh.setText(null);
//         this.txtGiaThanhXuat.setText(null);
//         this.txtSoLuong.setText(null);
//         this.txtNgayNhap.setText(null);
//         this.txtID.setText(null);
//         this.txtNhaCungCap.setText(null);
//         this.txtTenPhuTung.setText(null);
//         showtbNhapPhuTung();
         
         
         this.txtID.setText(null);
         this.txtNhanVienPhucVu.setText(null);
    
            this.txtNgayNhan.setText(null);
            this.txtTenKhachHang.setText(null);
            this.txtBienKiemSoat.setText(null);
            this.txtDienThoai.setText(null);
            this.txtNgayGiao.setText(null);
             this.txtNhanVienSuaChua.setText(null);
              this.txtTinhTrangTruoc.setText(null);
               this.txtNgayTra.setText(null);
                this.txtTongPhi.setText(null);
                 this.txtTinhTrangSau.setText(null);
                 showtbPhieuSuaChua();
         
    }//GEN-LAST:event_btnResetActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        int row = tbPhieuSuaChua.getSelectedRow();
        if(row != -1 ){
        ChiTietSuaChua ctsc = new ChiTietSuaChua();
        this.setVisible(false);
        ctsc.setVisible(true);
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PhieuSuaChua.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PhieuSuaChua.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PhieuSuaChua.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PhieuSuaChua.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PhieuSuaChua().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnPrint;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnXemThongKe;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JLabel lbPhieuSuaChua;
    private javax.swing.JTable tbPhieuSuaChua;
    private javax.swing.JTextField txtBienKiemSoat;
    private javax.swing.JTextField txtDienThoai;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtNgayGiao;
    private javax.swing.JTextField txtNgayNhan;
    private javax.swing.JTextField txtNgayTra;
    private javax.swing.JTextField txtNhanVienPhucVu;
    private javax.swing.JTextField txtNhanVienSuaChua;
    private javax.swing.JTextField txtTenKhachHang;
    private javax.swing.JTextArea txtTinhTrangSau;
    private javax.swing.JTextArea txtTinhTrangTruoc;
    private javax.swing.JTextField txtTongPhi;
    // End of variables declaration//GEN-END:variables
}
